### PR TITLE
Add environment and auto populate vars

### PR DESCRIPTION
**Pull request by benlower**
Adding a new Postman environment called "Tableau Webhooks" that contains all the variables needed to drive the collection. Also includes an update to the collection that will automatically set the environment variables for Site ID and Auth Token.

### CODE REVIEW

**Comment by mbren** [comment]
Hi @benlower , 

This looks great. I noticed 2 things:

1. Your updated Postman-Collection-Tableau-Webhooks.json file still contains a variable section in the JSON that defines variables you're now configuring in your new environment file. (Take a look at the very end of the Postman-Collection-Tableau-Webhooks.json in the "variable" section).

2. The new Tableau-Webhooks.postman_environment.json file doesn't define a value for "Webhook_ID". It should be there, because it's used in the "Get a webhook", "Delete a webhook", and "Test a webhook" endpoints.

**Comment by mbren** [comment]
Optionally, leave the values in the Initial Value column of the environment blank and set all the Current Value column values (other than REST_API_Version) to "TODO_CHANGE_ME".

**Comment by mbren** [comment]
I submitted a PR (https://github.com/tableau/webhooks-docs/pull/4) to update the docs to reflect your changes so you can merge that when you check this in.

**Comment by bcantoni** [comment]
This older PR was superseded by #9 which added the Postman file to the repo.

**Pull request closed without merging**
