### PR TITLE
Adding postman file for webhooks

### PR DESCRIPTION
**Pull request by benlower**
This is a collection to be used in Postman.

### CODE REVIEW

**Comment by bheem123** [comment]
Does this work with Tableau Online only? I tried to use webhooks to get notified when my extract on Tableau Server fails, and I received the following error from my server.

{
    "error": {
        "summary": "Resource Not Found",
        "detail": "Unknown resource '/exp/sites/ff66e08b-e7b4-4759-b21f-1fdc0e0885f9/webhooks/<Replace_Me>/test' specified in URI.",
        "code": "404003"
    }
}

Thanks
-Bheem

**Comment by seanmakesgames** [comment]
> Does this work with Tableau Online only? I tried to use webhooks to get notified when my extract on Tableau Server fails, and I received the following error from my server.
> 
> {
> "error": {
> "summary": "Resource Not Found",
> "detail": "Unknown resource '/exp/sites/ff66e08b-e7b4-4759-b21f-1fdc0e0885f9/webhooks/<Replace_Me>/test' specified in URI.",
> "code": "404003"
> }
> }
> 
> Thanks
> -Bheem

Hey @bheem123 - We are still working to get this feature rolled out and released. This was for hackathon and TC preview purposes. Join the developer program to get updates on this release and others!
https://www.tableau.com/developer

**Comment by bheem123** [comment]
Yes, I joined the developer program long time ago. I love this feature. I am looking for an event based trigger to notify me when a critical refresh fails. Please keep me posted when this is available for public on Server 2018 and beyond.

I don't think there is any tool that can do this now.

Thanks
-Bheem

________________________________

**Comment by bcantoni** [comment]
This older PR was superseded by #9 which added the Postman file to the repo.

**Pull request closed without merging**
